# Generated by Django 4.1.1 on 2022-09-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_photo'),
        ('models', '0003_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='engine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='nm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='series',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='series',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.model'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
